package cn.heweiming.ssm.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_dictionary
 *
 * @mbg.generated do_not_delete_during_merge Sat Sep 23 16:56:17 CST 2017
 */
public class Dictionary implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.id
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.NAME
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.CODE
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.type
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.content
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.description
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.remark
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.state
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String state;

    /**
     * Database Column Remarks:
     *   激活的
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.activated
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private Boolean activated;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.created_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.created_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最后修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.last_modified_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.last_modified_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.remark2
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.id
     *
     * @return the value of t_dictionary.id
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.id
     *
     * @param id the value for t_dictionary.id
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.NAME
     *
     * @return the value of t_dictionary.NAME
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.NAME
     *
     * @param name the value for t_dictionary.NAME
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.CODE
     *
     * @return the value of t_dictionary.CODE
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withCode(String code) {
        this.setCode(code);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.CODE
     *
     * @param code the value for t_dictionary.CODE
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.type
     *
     * @return the value of t_dictionary.type
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.type
     *
     * @param type the value for t_dictionary.type
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.content
     *
     * @return the value of t_dictionary.content
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withContent(String content) {
        this.setContent(content);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.content
     *
     * @param content the value for t_dictionary.content
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.description
     *
     * @return the value of t_dictionary.description
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.description
     *
     * @param description the value for t_dictionary.description
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.remark
     *
     * @return the value of t_dictionary.remark
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.remark
     *
     * @param remark the value for t_dictionary.remark
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.state
     *
     * @return the value of t_dictionary.state
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withState(String state) {
        this.setState(state);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.state
     *
     * @param state the value for t_dictionary.state
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.activated
     *
     * @return the value of t_dictionary.activated
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Boolean getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withActivated(Boolean activated) {
        this.setActivated(activated);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.activated
     *
     * @param activated the value for t_dictionary.activated
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.created_by
     *
     * @return the value of t_dictionary.created_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withCreatedBy(String createdBy) {
        this.setCreatedBy(createdBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.created_by
     *
     * @param createdBy the value for t_dictionary.created_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.created_date
     *
     * @return the value of t_dictionary.created_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withCreatedDate(LocalDateTime createdDate) {
        this.setCreatedDate(createdDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.created_date
     *
     * @param createdDate the value for t_dictionary.created_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.last_modified_by
     *
     * @return the value of t_dictionary.last_modified_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withLastModifiedBy(String lastModifiedBy) {
        this.setLastModifiedBy(lastModifiedBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.last_modified_by
     *
     * @param lastModifiedBy the value for t_dictionary.last_modified_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.last_modified_date
     *
     * @return the value of t_dictionary.last_modified_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public LocalDateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.last_modified_date
     *
     * @param lastModifiedDate the value for t_dictionary.last_modified_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.remark2
     *
     * @return the value of t_dictionary.remark2
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Dictionary withRemark2(String remark2) {
        this.setRemark2(remark2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.remark2
     *
     * @param remark2 the value for t_dictionary.remark2
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }
}