package cn.heweiming.ssm.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_login_log
 *
 * @mbg.generated do_not_delete_during_merge Sat Sep 23 17:10:49 CST 2017
 */
public class LoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.id
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.username
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.login_time
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private LocalDateTime loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.login_ip
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.login_state
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private Boolean loginState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.login_browser
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private String loginBrowser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.screen_resolution
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private String screenResolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.operating_system
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private String operatingSystem;

    /**
     * Database Column Remarks:
     *   激活的
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.activated
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private Boolean activated;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.created_by
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.created_date
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最后修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.last_modified_by
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.last_modified_date
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.remark
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.id
     *
     * @return the value of t_login_log.id
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.id
     *
     * @param id the value for t_login_log.id
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.username
     *
     * @return the value of t_login_log.username
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.username
     *
     * @param username the value for t_login_log.username
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_time
     *
     * @return the value of t_login_log.login_time
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LocalDateTime getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withLoginTime(LocalDateTime loginTime) {
        this.setLoginTime(loginTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_time
     *
     * @param loginTime the value for t_login_log.login_time
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setLoginTime(LocalDateTime loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_ip
     *
     * @return the value of t_login_log.login_ip
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withLoginIp(String loginIp) {
        this.setLoginIp(loginIp);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_ip
     *
     * @param loginIp the value for t_login_log.login_ip
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_state
     *
     * @return the value of t_login_log.login_state
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public Boolean getLoginState() {
        return loginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withLoginState(Boolean loginState) {
        this.setLoginState(loginState);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_state
     *
     * @param loginState the value for t_login_log.login_state
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setLoginState(Boolean loginState) {
        this.loginState = loginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_browser
     *
     * @return the value of t_login_log.login_browser
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public String getLoginBrowser() {
        return loginBrowser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withLoginBrowser(String loginBrowser) {
        this.setLoginBrowser(loginBrowser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_browser
     *
     * @param loginBrowser the value for t_login_log.login_browser
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setLoginBrowser(String loginBrowser) {
        this.loginBrowser = loginBrowser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.screen_resolution
     *
     * @return the value of t_login_log.screen_resolution
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public String getScreenResolution() {
        return screenResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withScreenResolution(String screenResolution) {
        this.setScreenResolution(screenResolution);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.screen_resolution
     *
     * @param screenResolution the value for t_login_log.screen_resolution
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setScreenResolution(String screenResolution) {
        this.screenResolution = screenResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.operating_system
     *
     * @return the value of t_login_log.operating_system
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public String getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withOperatingSystem(String operatingSystem) {
        this.setOperatingSystem(operatingSystem);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.operating_system
     *
     * @param operatingSystem the value for t_login_log.operating_system
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.activated
     *
     * @return the value of t_login_log.activated
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public Boolean getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withActivated(Boolean activated) {
        this.setActivated(activated);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.activated
     *
     * @param activated the value for t_login_log.activated
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.created_by
     *
     * @return the value of t_login_log.created_by
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withCreatedBy(String createdBy) {
        this.setCreatedBy(createdBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.created_by
     *
     * @param createdBy the value for t_login_log.created_by
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.created_date
     *
     * @return the value of t_login_log.created_date
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withCreatedDate(LocalDateTime createdDate) {
        this.setCreatedDate(createdDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.created_date
     *
     * @param createdDate the value for t_login_log.created_date
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.last_modified_by
     *
     * @return the value of t_login_log.last_modified_by
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withLastModifiedBy(String lastModifiedBy) {
        this.setLastModifiedBy(lastModifiedBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.last_modified_by
     *
     * @param lastModifiedBy the value for t_login_log.last_modified_by
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.last_modified_date
     *
     * @return the value of t_login_log.last_modified_date
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LocalDateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.last_modified_date
     *
     * @param lastModifiedDate the value for t_login_log.last_modified_date
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.remark
     *
     * @return the value of t_login_log.remark
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public LoginLog withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.remark
     *
     * @param remark the value for t_login_log.remark
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbg.generated Sat Sep 23 17:10:49 CST 2017
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }
}