package cn.heweiming.ssm.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_menu
 *
 * @mbg.generated do_not_delete_during_merge Sat Sep 23 23:42:48 CST 2017
 */
public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.id
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.parent_id
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.name
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.url
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.code
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.icon
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.sorting
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private Short sorting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.class_name
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.description
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.type
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.state
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String state;

    /**
     * Database Column Remarks:
     *   激活的
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.activated
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private Boolean activated;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.created_by
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.created_date
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最后修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.last_modified_by
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.last_modified_date
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.remark
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.id
     *
     * @return the value of t_menu.id
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.id
     *
     * @param id the value for t_menu.id
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.parent_id
     *
     * @return the value of t_menu.parent_id
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withParentId(Integer parentId) {
        this.setParentId(parentId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.parent_id
     *
     * @param parentId the value for t_menu.parent_id
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.name
     *
     * @return the value of t_menu.name
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.name
     *
     * @param name the value for t_menu.name
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.url
     *
     * @return the value of t_menu.url
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withUrl(String url) {
        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.url
     *
     * @param url the value for t_menu.url
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.code
     *
     * @return the value of t_menu.code
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withCode(String code) {
        this.setCode(code);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.code
     *
     * @param code the value for t_menu.code
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.icon
     *
     * @return the value of t_menu.icon
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withIcon(String icon) {
        this.setIcon(icon);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.icon
     *
     * @param icon the value for t_menu.icon
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.sorting
     *
     * @return the value of t_menu.sorting
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Short getSorting() {
        return sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withSorting(Short sorting) {
        this.setSorting(sorting);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.sorting
     *
     * @param sorting the value for t_menu.sorting
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setSorting(Short sorting) {
        this.sorting = sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.class_name
     *
     * @return the value of t_menu.class_name
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withClassName(String className) {
        this.setClassName(className);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.class_name
     *
     * @param className the value for t_menu.class_name
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.description
     *
     * @return the value of t_menu.description
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.description
     *
     * @param description the value for t_menu.description
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.type
     *
     * @return the value of t_menu.type
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.type
     *
     * @param type the value for t_menu.type
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.state
     *
     * @return the value of t_menu.state
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withState(String state) {
        this.setState(state);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.state
     *
     * @param state the value for t_menu.state
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.activated
     *
     * @return the value of t_menu.activated
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Boolean getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withActivated(Boolean activated) {
        this.setActivated(activated);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.activated
     *
     * @param activated the value for t_menu.activated
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.created_by
     *
     * @return the value of t_menu.created_by
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withCreatedBy(String createdBy) {
        this.setCreatedBy(createdBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.created_by
     *
     * @param createdBy the value for t_menu.created_by
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.created_date
     *
     * @return the value of t_menu.created_date
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withCreatedDate(LocalDateTime createdDate) {
        this.setCreatedDate(createdDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.created_date
     *
     * @param createdDate the value for t_menu.created_date
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.last_modified_by
     *
     * @return the value of t_menu.last_modified_by
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withLastModifiedBy(String lastModifiedBy) {
        this.setLastModifiedBy(lastModifiedBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.last_modified_by
     *
     * @param lastModifiedBy the value for t_menu.last_modified_by
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.last_modified_date
     *
     * @return the value of t_menu.last_modified_date
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public LocalDateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.last_modified_date
     *
     * @param lastModifiedDate the value for t_menu.last_modified_date
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.remark
     *
     * @return the value of t_menu.remark
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public Menu withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.remark
     *
     * @param remark the value for t_menu.remark
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sat Sep 23 23:42:48 CST 2017
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }
}