package cn.heweiming.ssm.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_permissions
 *
 * @mbg.generated do_not_delete_during_merge Sat Sep 23 16:56:17 CST 2017
 */
public class Permissions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.id
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.NAME
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.url
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.method
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.state
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.type
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.genus_group
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String genusGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.description
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String description;

    /**
     * Database Column Remarks:
     *   激活的
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.activated
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private Boolean activated;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.created_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.created_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最后修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.last_modified_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.last_modified_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permissions.remark
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.id
     *
     * @return the value of t_permissions.id
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.id
     *
     * @param id the value for t_permissions.id
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.NAME
     *
     * @return the value of t_permissions.NAME
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.NAME
     *
     * @param name the value for t_permissions.NAME
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.url
     *
     * @return the value of t_permissions.url
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withUrl(String url) {
        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.url
     *
     * @param url the value for t_permissions.url
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.method
     *
     * @return the value of t_permissions.method
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withMethod(String method) {
        this.setMethod(method);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.method
     *
     * @param method the value for t_permissions.method
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.state
     *
     * @return the value of t_permissions.state
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withState(String state) {
        this.setState(state);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.state
     *
     * @param state the value for t_permissions.state
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.type
     *
     * @return the value of t_permissions.type
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.type
     *
     * @param type the value for t_permissions.type
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.genus_group
     *
     * @return the value of t_permissions.genus_group
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getGenusGroup() {
        return genusGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withGenusGroup(String genusGroup) {
        this.setGenusGroup(genusGroup);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.genus_group
     *
     * @param genusGroup the value for t_permissions.genus_group
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setGenusGroup(String genusGroup) {
        this.genusGroup = genusGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.description
     *
     * @return the value of t_permissions.description
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.description
     *
     * @param description the value for t_permissions.description
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.activated
     *
     * @return the value of t_permissions.activated
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Boolean getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withActivated(Boolean activated) {
        this.setActivated(activated);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.activated
     *
     * @param activated the value for t_permissions.activated
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.created_by
     *
     * @return the value of t_permissions.created_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withCreatedBy(String createdBy) {
        this.setCreatedBy(createdBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.created_by
     *
     * @param createdBy the value for t_permissions.created_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.created_date
     *
     * @return the value of t_permissions.created_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withCreatedDate(LocalDateTime createdDate) {
        this.setCreatedDate(createdDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.created_date
     *
     * @param createdDate the value for t_permissions.created_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.last_modified_by
     *
     * @return the value of t_permissions.last_modified_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withLastModifiedBy(String lastModifiedBy) {
        this.setLastModifiedBy(lastModifiedBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.last_modified_by
     *
     * @param lastModifiedBy the value for t_permissions.last_modified_by
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.last_modified_date
     *
     * @return the value of t_permissions.last_modified_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public LocalDateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.last_modified_date
     *
     * @param lastModifiedDate the value for t_permissions.last_modified_date
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permissions.remark
     *
     * @return the value of t_permissions.remark
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public Permissions withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permissions.remark
     *
     * @param remark the value for t_permissions.remark
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permissions
     *
     * @mbg.generated Sat Sep 23 16:56:17 CST 2017
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }
}