package cn.heweiming.ssm.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sys_user
 *
 * @mbg.generated do_not_delete_during_merge Sat Sep 23 00:37:09 CST 2017
 */
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.id
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.username
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.password
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.first_name
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.last_name
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.mobile
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.email
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.image_url
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.activated
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private Boolean activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.activation_key
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String activationKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.reset_key
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String resetKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.reset_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private Date resetDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.created_by
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.created_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.last_modified_by
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.last_modified_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private Date lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.remark
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.id
     *
     * @return the value of t_sys_user.id
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.id
     *
     * @param id the value for t_sys_user.id
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.username
     *
     * @return the value of t_sys_user.username
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.username
     *
     * @param username the value for t_sys_user.username
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.password
     *
     * @return the value of t_sys_user.password
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withPassword(String password) {
        this.setPassword(password);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.password
     *
     * @param password the value for t_sys_user.password
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.first_name
     *
     * @return the value of t_sys_user.first_name
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withFirstName(String firstName) {
        this.setFirstName(firstName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.first_name
     *
     * @param firstName the value for t_sys_user.first_name
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.last_name
     *
     * @return the value of t_sys_user.last_name
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withLastName(String lastName) {
        this.setLastName(lastName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.last_name
     *
     * @param lastName the value for t_sys_user.last_name
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.mobile
     *
     * @return the value of t_sys_user.mobile
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withMobile(String mobile) {
        this.setMobile(mobile);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.mobile
     *
     * @param mobile the value for t_sys_user.mobile
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.email
     *
     * @return the value of t_sys_user.email
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withEmail(String email) {
        this.setEmail(email);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.email
     *
     * @param email the value for t_sys_user.email
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.image_url
     *
     * @return the value of t_sys_user.image_url
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withImageUrl(String imageUrl) {
        this.setImageUrl(imageUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.image_url
     *
     * @param imageUrl the value for t_sys_user.image_url
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.activated
     *
     * @return the value of t_sys_user.activated
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public Boolean getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withActivated(Boolean activated) {
        this.setActivated(activated);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.activated
     *
     * @param activated the value for t_sys_user.activated
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.activation_key
     *
     * @return the value of t_sys_user.activation_key
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getActivationKey() {
        return activationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withActivationKey(String activationKey) {
        this.setActivationKey(activationKey);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.activation_key
     *
     * @param activationKey the value for t_sys_user.activation_key
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setActivationKey(String activationKey) {
        this.activationKey = activationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.reset_key
     *
     * @return the value of t_sys_user.reset_key
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getResetKey() {
        return resetKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withResetKey(String resetKey) {
        this.setResetKey(resetKey);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.reset_key
     *
     * @param resetKey the value for t_sys_user.reset_key
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setResetKey(String resetKey) {
        this.resetKey = resetKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.reset_date
     *
     * @return the value of t_sys_user.reset_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public Date getResetDate() {
        return resetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withResetDate(Date resetDate) {
        this.setResetDate(resetDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.reset_date
     *
     * @param resetDate the value for t_sys_user.reset_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setResetDate(Date resetDate) {
        this.resetDate = resetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.created_by
     *
     * @return the value of t_sys_user.created_by
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withCreatedBy(String createdBy) {
        this.setCreatedBy(createdBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.created_by
     *
     * @param createdBy the value for t_sys_user.created_by
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.created_date
     *
     * @return the value of t_sys_user.created_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withCreatedDate(Date createdDate) {
        this.setCreatedDate(createdDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.created_date
     *
     * @param createdDate the value for t_sys_user.created_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.last_modified_by
     *
     * @return the value of t_sys_user.last_modified_by
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withLastModifiedBy(String lastModifiedBy) {
        this.setLastModifiedBy(lastModifiedBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.last_modified_by
     *
     * @param lastModifiedBy the value for t_sys_user.last_modified_by
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.last_modified_date
     *
     * @return the value of t_sys_user.last_modified_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withLastModifiedDate(Date lastModifiedDate) {
        this.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.last_modified_date
     *
     * @param lastModifiedDate the value for t_sys_user.last_modified_date
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.remark
     *
     * @return the value of t_sys_user.remark
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public User withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.remark
     *
     * @param remark the value for t_sys_user.remark
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated Sat Sep 23 00:37:09 CST 2017
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }
}