debug: true
server:
  port: 8080
  context-path: /ssm
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: null
  redis:
    database: 0
    host: 120.77.181.175
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  thymeleaf:
    mode: HTML
    cache: false
mybatis:
  config-location: classpath:/config/mybatis-config.xml
  mapper-locations:
  - classpath:/mapper/*.xml
  - classpath:/dao/*.xml
flyway:
  enabled: false
crypto:
  rsa:
    private-key: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAoWsLp22/RBxSuKxXU4Iw6B3IaJUaTD1pYGTC1Vn1sJXfpW3+M4ZfoME6ExY8PzDXn+vnX2V315pa4GtXmg0ncQIDAQABAkB7eHg3n7kYDlowLJO3qvRh+LYdWT/+ZVM/ipOFwwQuB59H29TmFeYWdgJl+NEIUWZj9EwN8PMFYCIvK976r1cpAiEAy12MhoZN+iqeC3MDVYhdrpEi+XLOw2U32VhcWgB8UVMCIQDLMi6Di4rhFUsFOFcCcrWMSOAdJmGmvRxU5vtmhQ43qwIgJya+bBOlJXlY7elZhfj32Ci27AEvTyzIYL6DIQyg4mMCIQDGtN8pwtdgP6tqgmsMONLzSfzoZLVQElVXbb5hxjJeGwIhAMF2LCAolJ0KZEfYpMbGu8h+/tXN8n4Vd/yriyZ94myn